apiVersion: v1
kind: Pod
metadata:
  name: resnet-training
spec:
  containers:
    - name: resnet-training-container
      image: resnet-training:latest  # 모델 훈련을 위한 Docker 이미지
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /src/data  # 컨테이너 내에서 마운트할 경로
          name: data-storage
        - mountPath: /src/saved_models  # 컨테이너 내에서 마운트할 경로
          name: model-storage
      command:
        - /bin/sh
        - -c
        - |
          tail -f /dev/null

  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: model-storage-pvc  # PVC 이름
    - name: data-storage
      persistentVolumeClaim:
        claimName: data-storage-pvc